# Generated by Django 3.0.8 on 2020-07-01 16:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('parentOrg', models.CharField(max_length=30)),
                ('parentOrgOther', models.CharField(max_length=30)),
                ('dateOfBirth', models.CharField(max_length=30)),
                ('participantType', models.CharField(choices=[('regular', 'regular'), ('leader', 'leader'), ('small_child', 'small_child'), ('alumni', 'alumni'), ('staff', 'staff')], max_length=30)),
                ('rank', models.CharField(max_length=30)),
                ('rankLeader', models.CharField(max_length=30)),
                ('smallChildRef', models.CharField(max_length=30)),
                ('rate', models.CharField(max_length=30)),
                ('familyMember', models.CharField(max_length=30)),
                ('foodOptions', models.CharField(choices=[('vegetarian', 'vegetarian'), ('vegan', 'vegan'), ('meat', 'meat')], max_length=30)),
                ('maySwim', models.BooleanField()),
                ('requiredMedecine', models.CharField(max_length=30)),
                ('foodIntolerances', models.CharField(max_length=30)),
                ('allergies', models.CharField(max_length=30)),
                ('dayVisitor', models.BooleanField()),
                ('dayVisitorArrival', models.CharField(max_length=30)),
                ('dayVisitorDeparture', models.CharField(max_length=30)),
                ('dayVisitorArrivalMeal', models.CharField(max_length=30)),
                ('dayVisitorDepartureMeal', models.CharField(max_length=30)),
                ('tshirtSize', models.CharField(max_length=30)),
                ('awarenessTraining', models.CharField(max_length=30)),
                ('staffDays', models.CharField(max_length=30)),
                ('staffProfession', models.CharField(max_length=30)),
                ('staffLanguages', models.CharField(max_length=30)),
                ('staffLanguagesOther', models.CharField(max_length=30)),
                ('staffQualDrivingLicense', models.CharField(max_length=30)),
                ('staffQualChainsawLicense', models.BooleanField()),
                ('staffQualProfessionalDriver', models.BooleanField()),
                ('staffQualElectrician', models.BooleanField()),
                ('staffQualOther', models.CharField(max_length=30)),
                ('staffBackgroundCheck', models.BooleanField()),
                ('staffFancyAwarenessThingy', models.BooleanField()),
                ('staffInsured', models.BooleanField()),
                ('staffHasTent', models.BooleanField()),
                ('staffTentExtra', models.CharField(max_length=30)),
                ('staffOnsiteGuardian', models.CharField(max_length=30)),
                ('staffChildcare', models.CharField(max_length=30)),
                ('staffType', models.CharField(max_length=30)),
                ('staffSubtype', models.CharField(max_length=30)),
                ('staffSubcamp', models.CharField(max_length=30)),
                ('staffFreeDayVisitor', models.BooleanField()),
                ('medicalSheet', models.BooleanField()),
                ('pictureAgreement', models.BooleanField()),
                ('gdprAgreed', models.BooleanField()),
                ('agbAgreed', models.BooleanField()),
            ],
        ),
    ]
