# Generated by Django 3.0.8 on 2020-07-02 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participant',
            name='allergies',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='awarenessTraining',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dateOfBirth',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dayVisitorArrival',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dayVisitorArrivalMeal',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dayVisitorDeparture',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dayVisitorDepartureMeal',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='familyMember',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='foodIntolerances',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='parentOrg',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='parentOrgOther',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='rank',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='rankLeader',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='rate',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='requiredMedecine',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='smallChildRef',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffChildcare',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffDays',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffLanguages',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffLanguagesOther',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffOnsiteGuardian',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffProfession',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffQualDrivingLicense',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffQualOther',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffSubcamp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffSubtype',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffTentExtra',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffType',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='tshirtSize',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
