# Generated by Django 3.0.8 on 2020-07-06 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200702_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('misc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agbAgreedContact', models.BooleanField(default=False)),
                ('existingIntlGroup', models.CharField(blank=True, max_length=30)),
                ('contactName', models.CharField(blank=True, max_length=30)),
                ('thirdPlacementChoice', models.CharField(blank=True, max_length=30)),
                ('secondPlacementChoice', models.CharField(blank=True, max_length=30)),
                ('priceAdjustments', models.CharField(blank=True, max_length=30)),
                ('isIntlGroup', models.BooleanField(default=False)),
                ('wantIntlGroup', models.BooleanField(default=False)),
                ('agbAgreedOrg', models.BooleanField(default=False)),
                ('allowEarlyDeparture', models.BooleanField(default=False)),
                ('communalEarlyDeparture', models.BooleanField(default=False)),
                ('requireEarlyDeparture', models.BooleanField(default=False)),
                ('publicTransport', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('mixedOrg', models.BooleanField(default=False)),
                ('contactAddress', models.CharField(blank=True, max_length=30)),
                ('firstPlacementChoice', models.CharField(blank=True, max_length=30)),
                ('billingAddress', models.CharField(blank=True, max_length=30)),
                ('contactMail', models.CharField(blank=True, max_length=30)),
                ('contactPhone', models.CharField(blank=True, max_length=30)),
                ('extraText', models.CharField(blank=True, max_length=30)),
                ('parentOrg', models.CharField(blank=True, max_length=30)),
                ('parentOrgOther', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GuardianContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('misc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OwnContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='participant',
            name='agbAgreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dayVisitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gdprAgreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='maySwim',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='medicalSheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='pictureAgreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffBackgroundCheck',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffFancyAwarenessThingy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffFreeDayVisitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffHasTent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffInsured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffQualChainsawLicense',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffQualElectrician',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffQualProfessionalDriver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='emergencyContacts',
            field=models.ManyToManyField(default=None, null=True, related_name='participants', to='backend.EmergencyContact'),
        ),
        migrations.AddField(
            model_name='participant',
            name='guardianContact',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='backend.GuardianContact'),
        ),
        migrations.AddField(
            model_name='participant',
            name='ownContact',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='backend.OwnContact'),
        ),
    ]
