# Generated by Django 3.0.8 on 2020-07-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200706_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='address',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='email',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='fullName',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='misc',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='role',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='group',
            name='billingAddress',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='group',
            name='contactAddress',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='group',
            name='contactMail',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='group',
            name='contactName',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='group',
            name='contactPhone',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='group',
            name='existingIntlGroup',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='group',
            name='extraText',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='group',
            name='firstPlacementChoice',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='group',
            name='parentOrg',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='group',
            name='parentOrgOther',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='group',
            name='priceAdjustments',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='group',
            name='publicTransport',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='group',
            name='secondPlacementChoice',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='group',
            name='thirdPlacementChoice',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='guardiancontact',
            name='address',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='guardiancontact',
            name='email',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='guardiancontact',
            name='fullName',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='guardiancontact',
            name='misc',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='guardiancontact',
            name='phone',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='owncontact',
            name='address',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='owncontact',
            name='email',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='owncontact',
            name='phone',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='allergies',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='awarenessTraining',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dateOfBirth',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dayVisitorArrival',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dayVisitorArrivalMeal',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dayVisitorDeparture',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dayVisitorDepartureMeal',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='familyMember',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='foodIntolerances',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='foodOptions',
            field=models.CharField(choices=[('vegetarian', 'vegetarian'), ('vegan', 'vegan'), ('meat', 'meat')], max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='fullName',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='parentOrg',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='parentOrgOther',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participantType',
            field=models.CharField(choices=[('regular', 'regular'), ('leader', 'leader'), ('small_child', 'small_child'), ('alumni', 'alumni'), ('staff', 'staff')], max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='rank',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='rankLeader',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='rate',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='requiredMedecine',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='smallChildRef',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffChildcare',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffDays',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffLanguages',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffLanguagesOther',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffOnsiteGuardian',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffProfession',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffQualDrivingLicense',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffQualOther',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffSubcamp',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffSubtype',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffTentExtra',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffType',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='tshirtSize',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
