# Generated by Django 3.0.8 on 2020-07-07 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200707_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('misc', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
        migrations.AlterField(
            model_name='participant',
            name='emergencyContacts',
            field=models.ManyToManyField(default=None, null=True, related_name='participants_emergency', to='backend.Contact'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='guardianContact',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants_guardian', to='backend.Contact'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ownContact',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants_own', to='backend.Contact'),
        ),
        migrations.DeleteModel(
            name='GuardianContact',
        ),
        migrations.DeleteModel(
            name='OwnContact',
        ),
    ]
