# Generated by Django 3.0.8 on 2020-07-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200707_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='misc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dateOfBirth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dayVisitorArrival',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dayVisitorDeparture',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='foodIntolerances',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='requiredMedecine',
            field=models.TextField(blank=True),
        ),
    ]
