# Generated by Django 3.0.8 on 2020-08-02 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0006_auto_20200707_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='agbAgreed',
            field=models.BooleanField(default=False, help_text='Der Teilnehmer hat den Lager AGB zugestimmt.', verbose_name='AGB-Einverständnis'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='allergies',
            field=models.TextField(blank=True, help_text='Freitextfeld, um Allergien anzugeben', verbose_name='Allergien'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='awarenessTraining',
            field=models.CharField(blank=True, help_text='Teilnehmer über 18 Jahre müssen eine Schutzschulung bezüglich sexualisierter Gewalt vorweisen', max_length=60, verbose_name='Schutzschulung'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dateOfBirth',
            field=models.DateField(blank=True, help_text='Geschlecht, ist momentan Freitext im Backend.', verbose_name='Geburtstag'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dayVisitor',
            field=models.BooleanField(default=False, help_text='Tagesbesucher, falls der Teilnehmer nicht ganze Zeit da ist.', verbose_name='Tagesbesucher'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dayVisitorArrival',
            field=models.DateField(blank=True, help_text='Anreisetag bei Tagesbesucher.', verbose_name='Anreisetag'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dayVisitorArrivalMeal',
            field=models.CharField(blank=True, help_text='UNKLAR: Was soll hier passieren? Ist das ggfs. ein Boolean?', max_length=60, verbose_name='Essen am Anreisetag'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dayVisitorDeparture',
            field=models.DateField(blank=True, help_text='Abreisetag bei Tagesbesucher.', verbose_name='Abreisetag'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dayVisitorDepartureMeal',
            field=models.CharField(blank=True, help_text='UNKLAR: Was soll hier passieren? Ist das ggfs. ein Boolean?', max_length=60, verbose_name='Essen am Abreisetag'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='familyMember',
            field=models.CharField(blank=True, help_text='UNKLAR: Familienmitglied? Freitext-Feld', max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='foodIntolerances',
            field=models.TextField(blank=True, help_text='Freitextfeld, um Lebensmittel-Unverträglichkeiten einzugeben.', verbose_name='Lebensmittel-Unverträglichkeiten'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='foodOptions',
            field=models.CharField(choices=[('vegetarian', 'vegetarian'), ('vegan', 'vegan'), ('meat', 'meat')], help_text='Auswahl der Essens-Art.', max_length=60, verbose_name='Essen'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='fullName',
            field=models.CharField(help_text='Voller Name, Vorname und Nachname', max_length=60, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gdprAgreed',
            field=models.BooleanField(default=False, help_text='Der Teilnehmer ist mit der Lager-Datenschutzerklärung einverstanden.', verbose_name='Datenschutz-Einverständnis'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(blank=True, help_text='Geschlecht, ist momentan Freitext im Backend', max_length=60, verbose_name='Geschlecht'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='maySwim',
            field=models.BooleanField(default=False, help_text='Ja: Teilnehmer hat Schwimmerlaubnis', verbose_name='Darf Schwimmen'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='medicalSheet',
            field=models.BooleanField(default=False, help_text='UNKLAR'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='owner',
            field=models.ForeignKey(help_text='Benutzer, dem dieser Teilnehmereintrag gehoert', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='Besitzer'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='parentOrg',
            field=models.CharField(blank=True, help_text='UNKLAR', max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='parentOrgOther',
            field=models.CharField(blank=True, help_text='UNKLAR', max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participantType',
            field=models.CharField(choices=[('regular', 'regular'), ('leader', 'leader'), ('small_child', 'small_child'), ('alumni', 'alumni'), ('staff', 'staff')], help_text='Teilnehmer Typ, evtl. können wir darüber Berechtigungen ableiten?', max_length=60, verbose_name='Teilnehmer-Typ'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='pictureAgreement',
            field=models.BooleanField(default=False, help_text='Der Teilnehmer hat sein Einverständnis gegeben, dass er auf Lagerbildern abgebildet werden darf.', verbose_name='Bild-Einverständnis'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='rank',
            field=models.CharField(blank=True, help_text='UNKLAR: Stufe? Freitext-Feld', max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='rankLeader',
            field=models.CharField(blank=True, help_text='UNKLAR: Stufenleiter? Freitext-Feld', max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='rate',
            field=models.CharField(blank=True, help_text='Beitrags-Rate. Berechnung soll im Backend passieren. UNKLAR: Momentan TODO', max_length=60, verbose_name='Beitrags-Rate'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='requiredMedecine',
            field=models.TextField(blank=True, help_text='Freitextfeld, um benötigte Medikamente eintragen zu können.', verbose_name='Benötigte Medikamente'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='smallChildRef',
            field=models.CharField(blank=True, help_text='UNKLAR: Link auf Kind? Freitext-Feld', max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffBackgroundCheck',
            field=models.BooleanField(default=False, help_text='Das Führungszeugnis des Helfers wurde zwecks Schutz vor sexualisierter Gewalt geprüft.', verbose_name='Führungszeugnis-Einsicht'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffChildcare',
            field=models.CharField(blank=True, help_text='UNKLAR', max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffDays',
            field=models.CharField(blank=True, help_text='UNKLAR: Soll auch noch ein String-Array sein?', max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffFancyAwarenessThingy',
            field=models.BooleanField(default=False, help_text='UNKLAR'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffFreeDayVisitor',
            field=models.BooleanField(default=False, help_text='UNKLAR'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffHasTent',
            field=models.BooleanField(default=False, help_text='Der Helfer hat ein eigenes Zelt dabei.', verbose_name='Eigenes Zelt'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffInsured',
            field=models.BooleanField(default=False, help_text='UNKLAR'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffLanguages',
            field=models.CharField(blank=True, help_text='Liste mit Sprachen die der Helfer sprechen kann.', max_length=60, verbose_name='Sprachkentnisse'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffLanguagesOther',
            field=models.CharField(blank=True, help_text='UNKLAR', max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffOnsiteGuardian',
            field=models.CharField(blank=True, help_text='UNKLAR', max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffProfession',
            field=models.CharField(blank=True, help_text='UNKLAR', max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffQualChainsawLicense',
            field=models.BooleanField(default=False, help_text='Der Helfende verfügt über einen Kettensägen-Schein und darf eine Kettensäge führen.', verbose_name='Kettensägen-Schein'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffQualDrivingLicense',
            field=models.CharField(blank=True, help_text='Verfügbare Führerschein(e) des Helfers.', max_length=60, verbose_name='Führerschein'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffQualElectrician',
            field=models.BooleanField(default=False, help_text='Helfer ist ein gelernter Elektriker', verbose_name='Elektriker'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffQualOther',
            field=models.CharField(blank=True, help_text='Weitere nützliche Qualifikationen des Helfers', max_length=60, verbose_name='Weitere Qualifikationen'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffQualProfessionalDriver',
            field=models.BooleanField(default=False, help_text='Der helfende ist ein Berufsfahrer (Ja/Nein)', verbose_name='Berufsfahrer'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffSubcamp',
            field=models.CharField(blank=True, help_text='UNKLAR', max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffSubtype',
            field=models.CharField(blank=True, help_text='UNKLAR', max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffTentExtra',
            field=models.CharField(blank=True, help_text='UNKLAR', max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffType',
            field=models.CharField(blank=True, help_text='UNKLAR', max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='tshirtSize',
            field=models.CharField(blank=True, help_text='T-Shirt Größe für Lagershirt. UNKLAR: Soll das ein Auswahlfeld werden? XXS, XS, S, M, L, XL, XXL?', max_length=60, verbose_name='T-Shirt Größe'),
        ),
    ]
