# Generated by Django 3.0.8 on 2020-08-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_group_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='smallChildRef',
        ),
    ]
