# Generated by Django 3.0.8 on 2020-08-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_participant_smallchildref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='emergencyContacts',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='smallChildRef',
        ),
    ]
