# Generated by Django 3.0.8 on 2020-08-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20200811_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='emergencyContacts',
            field=models.ManyToManyField(default=None, help_text='Falls weitere Notfall-Kontaktdaten benötigt werden', null=True, related_name='participants_emergency', to='backend.Contact', verbose_name='Weitere Notfall-Kontaktdaten'),
        ),
        migrations.AddField(
            model_name='participant',
            name='smallChildRef',
            field=models.ManyToManyField(blank=True, default=None, help_text="Die Kategorie 'Kinder unter sechs Jahren' ist nur für Kinder gedacht, die mit einer erziehungsberechtigten Person anreisen und nicht am Programm teilnehmen. Dieses Feld ist ein String Feld mit dem 'FullName' des Erziehungsberechtigten. Im Hintergrund prüft und verküpft das Backend den FullName mit einem oder mehreren (falls FullName nicht eindeutig ist) existierenden Teilnehmern.", related_name='children', to='backend.Participant', verbose_name='Erziehungsberechtigter'),
        ),
    ]
