# Generated by Django 3.0.8 on 2020-08-12 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0017_participant_familymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='more_owners',
            field=models.ManyToManyField(default=None, help_text="Ein weiteres Array Feld, in dem das FrontEnd E-Mails ablegen kann, falls für die jeweilige Mail ein Benutzer gefunden wird, wird er hier verlinkt und erhält dann automatisch 'Owner' Rechte auf die Gruppe", null=True, related_name='more_grps', to=settings.AUTH_USER_MODEL, verbose_name='Weitere Besitzer'),
        ),
        migrations.AddField(
            model_name='participant',
            name='group',
            field=models.ForeignKey(default=1, help_text='Die Gruppierung des Teilnehmers', on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='backend.Group', verbose_name='Gruppierung'),
            preserve_default=False,
        ),
    ]
