# Generated by Django 3.0.8 on 2020-08-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20200812_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='dayVisitorArrival',
            field=models.DateField(blank=True, help_text='Anreisetag bei Tagesgast.', null=True, verbose_name='Anreisetag'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dayVisitorDeparture',
            field=models.DateField(blank=True, help_text='Abreisetag bei Tagesgast.', null=True, verbose_name='Abreisetag'),
        ),
    ]
