# Generated by Django 3.0.8 on 2020-08-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20200831_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='priceAdjustments',
            field=models.CharField(blank=True, help_text='Damit die Teilnehmenden bei der Anmeldung den für sie gültigen Preis sehen können.', max_length=600, verbose_name='Individuelle Preise'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffChildcare',
            field=models.CharField(blank=True, help_text='Kinderbetreuung für die Kinder des Helfers. Alle mitgebrachten Kinder müssen separat zum Lager angemeldet werden.', max_length=300, verbose_name='Kinderbetreuung'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffDays',
            field=models.CharField(blank=True, help_text='An welchen Tagen stehst der Teilnehmer als Helfer zur Verfügung? Eigentlich ein Date-Array, aber da muss ich noch schauen, wie das am besten in DB landet. Denke String List ist am einfachsten.', max_length=300, verbose_name='Tage als Helfer'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffLanguages',
            field=models.CharField(blank=True, help_text='Liste mit Sprachen die der Helfer sprechen kann (sehr gut bis fließend).', max_length=300, verbose_name='Sprachkentnisse'),
        ),
    ]
