# Generated by Django 3.0.8 on 2020-09-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20200831_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='rank',
            field=models.CharField(blank=True, choices=[(1, 'Wölflinge (1)'), (2, 'Jungpfadfinder (2)'), (3, 'Pfadfinder (3'), (4, 'Rover (4)')], help_text='Die Altersstufe des Teilnehmers, da unterschiedlich je nach Verband, muss das im Frontend gefiltert sein.', max_length=60, verbose_name='Altersstufe'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='tshirtSize',
            field=models.CharField(blank=True, choices=[('122-128', '122-128'), ('134-140', '134-140'), ('146-154', '146-154'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], help_text='T-Shirt Größe für Lagershirt', max_length=60, verbose_name='T-Shirt Größe'),
        ),
    ]
