# Generated by Django 3.0.8 on 2020-09-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20200901_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='publicTransport',
            field=models.CharField(blank=True, choices=[('train', 'Bahn'), ('bus', 'Bus'), ('other', 'Keine Anreise mit ÖPNV')], help_text="Wir müssen die öffentlichen Verkehrsbetriebe rechtzeitig über die zu erwartenden Passagierzahlen informieren, damit diese genug Kapazitäten bereitstellen können. Falls euer Stamm plant, mit den öffentlichen Verkehrsmitteln per Bus oder Bahn anzureisen, gebt dies bitte hier an. Wenn ihr die Anreise anderweitig organisiert, etwa mit einem eigenen Bus, wählt bitte 'Keine Anreise mit ÖPNV'", max_length=60, verbose_name='Anreise mit öffentlichen Verkehrsmitteln'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dayVisitorArrivalMeal',
            field=models.CharField(blank=True, choices=[('breakfast', 'Frühstück'), ('lunch', 'Mittagessen'), ('dinner', 'Abendessen')], help_text='Letzte noch genutzte Malzeit am Anreisetag.', max_length=60, verbose_name='Essen am Anreisetag'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='dayVisitorDepartureMeal',
            field=models.CharField(blank=True, choices=[('breakfast', 'Frühstück'), ('lunch', 'Mittagessen'), ('dinner', 'Abendessen')], help_text='Letzte noch genutzte Malzeit am Abreisetag.', max_length=60, verbose_name='Essen am Abreisetag'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participantType',
            field=models.CharField(blank=True, choices=[('regular', 'Stammesmitglied (außer Leiter)'), ('leader', 'Leiter*in'), ('small_child', 'Kinder unter sechs Jahren'), ('alumni', 'Ehemalige'), ('staff', 'Helfende')], help_text='Teilnehmer Typ, evtl. können wir darüber Berechtigungen ableiten?', max_length=60, verbose_name='Teilnehmerkategorie'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffSubtype',
            field=models.CharField(blank=True, choices=[('cafe', 'Cafe'), ('themeyurt', 'Themenjurte'), ('equipment', 'Ausrüster'), ('infrastructure', 'Infrastruktur'), ('content', 'Inhalt'), ('international', 'Internationales'), ('jumper', 'Springer')], help_text='In welchem Bereich der Helfer sich engagieren möchte', max_length=60, verbose_name='Mithilfe in Bereich'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='staffType',
            field=models.CharField(blank=True, choices=[('subcamp', 'Mithilfe in einem Unterlager'), ('central', 'Mithilfe in der zentralen Organisation')], help_text='Ob der Helfer in einem Bereich oder Unterlager sich engangieren möchte.', max_length=60, verbose_name='Helfendenkategorie'),
        ),
    ]
