# Generated by Django 3.0.8 on 2020-09-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20200902_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='foodOptions',
            field=models.CharField(blank=True, choices=[('vegetarian', 'Vegetarisch'), ('vegan', 'Vegan'), ('meat', 'Fleisch')], help_text='Auswahl der Essens-Art.', max_length=60, verbose_name='Essen'),
        ),
    ]
