# Generated by Django 3.0.8 on 2020-09-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_auto_20200902_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='parentOrg',
            field=models.CharField(blank=True, choices=[('DPSG Rottenburg-Stuttgart', 'DPSG Rottenburg-Stuttgart'), ('PSG Rottenburg-Stuttgart', 'PSG Rottenburg-Stuttgart'), ('DPSG Freiburg', 'DPSG Freiburg'), ('PSG Freiburg', 'PSG Freiburg'), ('VCP Baden', 'VCP Baden'), ('VCP Württemberg', 'VCP Württemberg'), ('BdP Baden-Württemberg', 'BdP Baden-Württemberg'), ('International guest', 'International guest')], help_text='Pfadfinder-Verband des Teilnehmers, z.B. DPSG, PSG, BDP ...', max_length=60, verbose_name='Verbandszugehörigkeit'),
        ),
    ]
